[versions]
clikt = "5.0.0"
# https://github.com/google/guice/issues/1798
guava = { strictly = "33.3.1-jre" }
guice = "7.0.0"
jimfs = "1.3.0"
junit = "5.11.0"
kotlin = "2.0.20"
kotlin-inline-logger = "1.0.6"
logback-classic = "1.5.8"
ktfmt-gradle = "0.20.1"
mockk = "1.13.12"
netty = "4.1.113.Final"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktfmt-gradle = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt-gradle" }

[libraries]
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
guice = { module = "com.google.inject:guice", version.ref = "guice" }
jimfs = { module = "com.google.jimfs:jimfs", version.ref = "jimfs" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-classic" }
kotlin-inline-logger = { module = "com.michael-bull.kotlin-inline-logger:kotlin-inline-logger", version.ref = "kotlin-inline-logger" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
netty-all = { module = "io.netty:netty-all", version.ref = "netty" }
